### ISSUE TITLE
Format of the Client Info page doesn't make sense (some selections)

### ISSUE THREAD

**Issue by joshsimard** [joshsimard/COMP4350-Project#37]
![GitHub Logo](/images/logo.png)
- _Gender should be a dropdown or radio buttons_
- _Date should be 3 drop downs_
- _Phone number can be just one number (no need for Home Phone)_
- _Phone number can have a box for ext. and box for rest of number_
- _Country and province/state should be a dropdown (will be difficult as country selection must populate the state or province based on the country; maybe worry about it for later iterations)_
- _Marital status should be a drop down (divorced, married, single, widowed, etc)

**Comment by Daskott** [comment]
Resolved!
